### ISSUE TITLE
Manifests from rhizome.get_bundlelist() don't contain custom fields 

### ISSUE THREAD

**Issue by jonashoechst** [umr-ds/pyserval#16]
When reading bundles through `rhizome.get_bundlelist()`, their manifests are missing custom fields. 

The get_bundlelist restful endpoint doesn't serve the original manifest, but only the most important fields. I suggest to 

1. either querying every manifest after creation
2. or provide a reload_manifest method to be triggered by the user / before calling update_manifest.

**Comment by CryptoCopter** [comment]
Fixed in c8f60b6a2a47f1ae70d6949e1d61479341aa7204
