### ISSUE TITLE
Use own data types

### ISSUE THREAD

**Issue by jonashoechst** [umr-ds/pyserval#5]
Multiple points in the code implement the restful interface with the primitive data types instead of using the ones defined by the library. Examples are _SIDs_ vs. _ServalIdentity_

Let's discuss wether the primitive datatypes should be used or the higher-level objects are right here.

**Comment by CryptoCopter** [comment]
Will be implemented as part of #11 
Low-level components will use primitives, while high-level components will encapsulate into custom datatypes
