### ISSUE TITLE
Type-assertions fail for python2

### ISSUE THREAD

**Issue by jonashoechst** [umr-ds/pyserval#6]
Some __init__ methods assert that values coming from the restful interface are of type `str`.  While this is the case in python3, it fails for python2, as the type is unicode. 

Suggestion: remove type checks

**Comment by CryptoCopter** [comment]
Alternative suggestion: Typecheck for either str or unicode

**Comment by CryptoCopter** [comment]
Alternative alternative suggestion: check for instance of 'basestring'

see: https://docs.python.org/2/howto/unicode.html#the-unicode-type
